# Generated by Django 4.2.3 on 2023-08-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('gender_field', models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE'), ('O', 'OTHER')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('A', 'ADMIN'), ('S', 'STAFF'), ('U', 'USER')], max_length=20)),
            ],
        ),
    ]
