# Generated by Django 4.2.3 on 2023-08-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_remove_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='break_in',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='break_out',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='punch_in',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='punch_out',
            field=models.TimeField(null=True),
        ),
    ]
