# Generated by Django 4.2.3 on 2023-08-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_alter_attendance_break_in_alter_attendance_break_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_work',
            field=models.TimeField(null=True),
        ),
    ]
