# Generated by Django 4.2.3 on 2023-08-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_attendance_total_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='total_work',
        ),
    ]
