# Generated by Django 4.2.3 on 2023-08-02 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_remove_attendance_total_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender_field',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
