# Generated by Django 4.2.3 on 2023-08-03 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0008_remove_user_gender_field_remove_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.user')),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('punch_in', 'punch_in'), ('punch_out', 'punch_out'), ('break_in', 'break_in'), ('break_out', 'break_out')], max_length=30)),
                ('entry_time', models.DateTimeField()),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.timesheet')),
            ],
        ),
    ]
